name: powerman_win32
description: A plugin to listen to Win32 power events such as AC power state, display on/off, and suspend/resume.
version: 0.2.0
homepage: https://github.com/espresso3389/powerman_win32

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      windows:
        pluginClass: PowermanWin32PluginCApi
